name: test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update; sudo apt-get install libcurl4-openssl-dev
    - name: make
      run: make
    - name: make test
      run: make test
